language: node_js
git:
        depth: 999999
node_js:
        - "8"
before_install:
        - git clone --depth=1 --branch=build https://github.com/aleen42/PersonalWiki.git temp
        - mv -f temp/* ./
        - mv temp/.bookignore ./
        - git clone --depth=1 --branch=gh-pages https://github.com/aleen42/PersonalWiki.git gh-pages
before_deploy:
        - npm run gitbook:install
        - npm run gitbook:build
deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
        on:
                branch: docs
        local_dir: ./gh-pages/
        name: aleen42
        email: aleen42@vip.qq.com
